use sgmysqldb1;
create table T11 like T4;
select * from T11;
drop table if exists T6;
create table T6(
EMP_ID CHAR,
MANAGER_ID CHAR,
SUPERVISER_ID CHAR,
EMP_SALARY DECIMAL(10,2),
MANAGER_SALARY DECIMAL(15,2),
SUPERVISER_SALARY DECIMAL(16,2),
EMP_ADDRESS BLOB,
MANAGER_ADDRESS BLOB,
SUPERVISER_ADDRESS BLOB);
DROP TABLE IF EXIST T6;
INSERT INTO T6 VALUES ('A','B','C',2000.04,8000.50,6000.80,'EMPLOYEE NAME IS ALLEN AND HE LIVES IN FORTWORTH QUALIFICATIONS ARE UNDERGRADUATE','MANAGER NAME IS BARRY AND LIVES IN PLANO QUALIFICATIONS ARE POST GRADUATION','SUPERVISER NAME IS IRIS AND LIVES IN PLANO AND QUALIFICATIONS ARE GRADUATION');
SELECT * FROM T6;
INSERT INTO T6 VALUES ('D','E','F',1000.45,8000.60,10000.56,'EMPLOYEE NAME IS MACK AND LIVES IN INDIA AND QUALIFICATION IS HIGHSCHOOL DIPLOMA','MANAGER NAME IS STONE MILLER AND LIVES IN FORTWORTHAND QUALIFICATIONS ARE GRADUATION','SUPERVISER NAME HYATT AND LIVES IN FRISCO AND QUALIFICATIONS ARE PLUS 2');
INSERT INTO T6 VALUES ('G','H','I',6000.00,780000.89,8900.78,'EMPLOYEE NAME IS NICK AND LIVES IN SEATLE AND QUALIFICATIONS ARE NULL','MANAGER NAME AMANDA AND LIVES IN LONDON AND QUALIFICATIONS ARE DEGREE','SUPERVISER NAME IS NICHOLAS AND LIVES IN UK AND LIUVES IN AMERICA');
INSERT INTO T6 VALUES ('J','K','L',7900.89,567000.90,78980.90,'EMPLOYEE NAME IS GARCE AND LIVES IN AUBREY AND QUALIFICATIONS ARE INTER','MANAGER NAME IS PAUL AND LIVES IN PLANO QUALIFICATIONS ARE DEGREE','SUPERVISER NAME IS MELISSA AND LIVES IN NIGERIA AND QUALIFICATIONS ARE DEGREE');
INSERT INTO T6 VALUES ('M','N','O',6789.00,78909.90,8976.90,'EMPLOYEE NAME IS SUNNY AND LIVES IN AMERICA AND QUALIFICATIONS ARE NOT AVAILABLE','MANAGER NAME IS HICKORY AND LIVES IN SA,AND QUALIFICATIONS ARE PHD','SUPERVISER NAME IS FUNKY AND LIVES IN NIGERIA ANS QUALIFICATIONS ARE NOTHING');
DELETE FROM T6 WHERE MANAGER_SALARY=78909.90;
INSERT INTO T6 VALUES('P','Q','R',6759.90,8976.90,876589.90,'EMPLYEE NAME IS HEDERICK AND QUALIFICATIONS ARE DEGREE AND LIVES IN CALIFORNIA','MANAGER NAME IS LEENA QUALIFICATIONS ARE DEGREE LIVES IN FLORIDA','SUPERVISER NAME IS MACK LIVES IN FLORIDA QUALIFIVCATIONS ARE NULL');
INSERT INTO T6 VALUES ('S','T','U',678909.90,8976509.90,8765490.90,'EMPLOYEE NAME IS SUSAN LIVES IN OMAHA QUALIFICATIONS ARE DEGREE','MANAGER NAME IS TIA AND LIVES IN PLANO QUALIFICATIONS ARE NULL','SUPERVISER NAME IS UTAH LIVES IN UTAH QUALIFICATIONS ARE INTER');
INSERT INTO T6 VALUES('V','W','X',98009,980790,890980,'EMPLOYEE NAME IS VOLA AND LIVES IN GEORGIA AND QUALIFICATIONS ARE HISCHOOL','MANAGER NAME IS WALTER LIVES IN UTAH QUALIFICATIONS ARE NULL','SUPERVISER LIVES IN PLANO AND NAME NOY AVAILABLE');
INSERT INTO T6 VALUES ('Y','Z','A',1000.45,8000.60,10000.56,'EMPLOYEE NAME IS MACK AND LIVES IN INDIA AND QUALIFICATION IS HIGHSCHOOL DIPLOMA','MANAGER NAME IS STONE MILLER AND LIVES IN FORTWORTHAND QUALIFICATIONS ARE GRADUATION','SUPERVISER NAME HYATT AND LIVES IN FRISCO AND QUALIFICATIONS ARE PLUS 2');
INSERT INTO T6 VALUES ('A','R','T',678900,987990,89765,'A IS ALREADY AN EMPLYEE ITS A DUPLICATE RECORD','R IS ALREADY AN EMPLYEE ITS A DUPLICATE RECORD','T IS ALREADY AN EMPLYEE ITS A DUPLICATE RECORD');
DELETE FROM T6 WHERE MANAGER_ADDRESS='MANAGER NAME IS PAUL AND LIVES IN PLANO QUALIFICATIONS ARE DEGREE';
DELETE FROM T6 WHERE EMP_SALARY BETWEEN 1000 AND 3000;
DELETE FROM T6 WHERE SUPERVISER_ID='T';
DELETE FROM T6 WHERE EMP_SALARY=6000;