use sgmysqldb1;
CREATE TABLE T7(
STUDENT_NAME VARCHAR(20),
GENDER CHAR,
RESULTS CHAR,
PROMOTING CHAR,
MARKS_AVG DECIMAL(5,2),
ZIPCODE DECIMAL(8,2),
PREFINAL_MARKS_AVG DECIMAL(5,2),
STUDENT_ADDRESS BLOB,
STUDENT_ASSESSMENT BLOB,
STUDENT_GRP_TEACHERS BLOB);
INSERT INTO T7 VALUES('ALLEN','M','P','Y',78.98,98767,89.90,'MALLESSIA,HATHWAY STREET,LIVES WITH GUARDIANS','GOOD BEHAVIOUR BUT LIL SHY','MS HEDRICK,LEENA,MACK,MEEK');
SELECT * FROM T7;
INSERT INTO T7 VALUES('BARRY','M','F','N',34.5,89007.00,56.09,'CALIFORNIA,MAIN STREET,SEVENTH FLLOR','FAILED NEED TO WORK OUT ON SUBJECTS','LEENA.HEDRICK,SALAS');
TRUNCATE TABLE T7;
DROP TABLE IF EXISTS T7;
INSERT INTO T7 VALUES ('IRIS','F','P','Y',89.98,78007,98.00,'FLORIDA,FIRST FLOOR PROS APARTMENT','PASSED IN DISTINCTION','FITTS,HEDRICK,SALAS');
INSERT INTO T7 VALUES ('NORA','F','P','Y',99.00,98007,89.98,'LIVES IN USA DONT KNOW EXACT ADDRESS','PASSED IN DISTINCTION','HYATT,MEEK,SHERRIL');
INSERT INTO T7 VALUES('KIARA','F','P','Y',78.87,78005,87.09,'LIVES IN INDIA HYDERABAD','PASSED IN FIRST CLASS','ELROD,FITTS,MELISSA');
INSERT INTO T7 VALUES ('TARA','F','F','N',32.90,98007,45.90,'LIVES IN FLORIDA ORLANDO','FAILED NEED TO WORK ON ALL SUBJECTS','MEEK,MELISSA,HEDRICK');
INSERT INTO T7 VALUES ('TIARA','F','P','Y',78.90,90879,89.98,'LIVES IN SEATLE BELLEVUE','PASSED IN FORST CLASS','MEEK,HEDRICK,FITTS');
INSERT INTO T7 VALUES ('KEERTHI','F','P','Y',36.00,89779,45.04,'LIVES IN UTAH','APPROACHED, NEED TO WORK ON ALL SUBJECTS','MEEK.FITTS,SHERRIL');
INSERT INTO T7 VALUES ('TEENA','F','F','N',32.09,89990,32.90,'LIVES IN PAKISTAN HYDERABADH','FAILED AND NEED TO STUDY MORE','LARA,TIARA,TARA');
INSERT INTO T7 VALUES ('LORREN','M','F','N',23.89,98007,32.68,'LIVES IN LONDON ITALY','FAILED BECAUSE DIDNT ATTEND SCHOOL MUCH','LARA,KIARA,TARA');
DELETE  FROM T7 WHERE MARKS_AVG BETWEEN 20 AND 30;
DELETE FROM T7 WHERE PREFINAL_MARKS_AVG LIKE '3%';
DELETE FROM T7 WHERE RESULTS='P' AND STUDENT_NAME LIKE 'K%';
